# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ports.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_COM_ports_program(object):
    def setupUi(self, COM_ports_program):
        COM_ports_program.setObjectName("COM_ports_program")
        COM_ports_program.setFixedSize(800, 574)
        COM_ports_program.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(COM_ports_program)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, -20, 801, 591))
        self.widget.setStyleSheet("\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 170, 255, 255), stop:1 rgba(255, 255, 255, 255));")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(150, 30, 71, 41))
        self.label.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"\n"
"font: 75 16pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(580, 30, 91, 41))
        self.label_2.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"\n"
"font: 75 16pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setGeometry(QtCore.QRect(400, 200, 20, 191))
        self.line.setStyleSheet("")
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.widget)
        self.line_2.setGeometry(QtCore.QRect(0, 180, 801, 16))
        self.line_2.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 170, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border-color: rgb(85, 255, 255);")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(90, 220, 221, 51))
        self.label_3.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"\n"
"\n"
"")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(150, 450, 81, 71))
        self.label_4.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"\n"
"font: 75 16pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.layoutWidget_2 = QtWidgets.QWidget(self.widget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(80, 310, 231, 26))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_12 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_12.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_4.addWidget(self.label_12)
        self.stop_bits = QtWidgets.QComboBox(self.layoutWidget_2)
        self.stop_bits.setStyleSheet("background-color: rgb(162, 243, 243);\n"
"")
        self.stop_bits.setObjectName("stop_bits")
        self.stop_bits.addItem("")
        self.stop_bits.addItem("")
        self.stop_bits.addItem("")
        self.horizontalLayout_4.addWidget(self.stop_bits)
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setGeometry(QtCore.QRect(510, 230, 211, 31))
        self.label_11.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"\n"
"\n"
"")
        self.label_11.setObjectName("label_11")
        self.input = QtWidgets.QLineEdit(self.widget)
        self.input.setGeometry(QtCore.QRect(30, 70, 311, 101))
        self.input.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.input.setObjectName("input")
        self.output = QtWidgets.QLineEdit(self.widget)
        self.output.setGeometry(QtCore.QRect(470, 70, 301, 101))
        self.output.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.output.setObjectName("output")
        self.clear = QtWidgets.QPushButton(self.widget)
        self.clear.setGeometry(QtCore.QRect(360, 110, 93, 28))
        self.clear.setStyleSheet("background-color: rgb(85, 255, 0);\n"
"font: 75 9pt \"MS Shell Dlg 2\";")
        self.clear.setObjectName("clear")
        self.status_input = QtWidgets.QTextBrowser(self.widget)
        self.status_input.setGeometry(QtCore.QRect(470, 280, 271, 61))
        self.status_input.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.status_input.setObjectName("status_input")
        self.line_5 = QtWidgets.QFrame(self.widget)
        self.line_5.setGeometry(QtCore.QRect(0, 390, 801, 16))
        self.line_5.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 170, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border-color: rgb(85, 255, 255);")
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.layoutWidget = QtWidgets.QWidget(self.widget)
        self.layoutWidget.setGeometry(QtCore.QRect(80, 280, 228, 23))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"border-right-color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_5.setLineWidth(0)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.name_com_ports = QtWidgets.QComboBox(self.layoutWidget)
        self.name_com_ports.setStyleSheet("background-color: rgb(162, 243, 243);\n"
"")
        self.name_com_ports.setObjectName("name_com_ports")
        self.name_com_ports.addItem("")
        self.name_com_ports.addItem("")
        self.horizontalLayout.addWidget(self.name_com_ports)
        self.debug = QtWidgets.QLineEdit(self.widget)
        self.debug.setGeometry(QtCore.QRect(320, 430, 321, 121))
        self.debug.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.debug.setDragEnabled(False)
        self.debug.setReadOnly(False)
        self.debug.setClearButtonEnabled(False)
        self.debug.setObjectName("debug")
        COM_ports_program.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(COM_ports_program)
        self.statusbar.setObjectName("statusbar")
        COM_ports_program.setStatusBar(self.statusbar)

        self.retranslateUi(COM_ports_program)
        QtCore.QMetaObject.connectSlotsByName(COM_ports_program)

    def retranslateUi(self, COM_ports_program):
        _translate = QtCore.QCoreApplication.translate
        COM_ports_program.setWindowTitle(_translate("COM_ports_program", "MainWindow"))
        self.label.setText(_translate("COM_ports_program", "Input"))
        self.label_2.setText(_translate("COM_ports_program", "Output"))
        self.label_3.setText(_translate("COM_ports_program", "Setting up COM-port"))
        self.label_4.setText(_translate("COM_ports_program", "Debug"))
        self.label_12.setText(_translate("COM_ports_program", "Stop Bits :"))
        self.stop_bits.setItemText(0, _translate("COM_ports_program", "1"))
        self.stop_bits.setItemText(1, _translate("COM_ports_program", "1,5"))
        self.stop_bits.setItemText(2, _translate("COM_ports_program", "2"))
        self.label_11.setText(_translate("COM_ports_program", "Status of COM-port"))
        self.input.setPlaceholderText(_translate("COM_ports_program", "Enter your message..."))
        self.output.setPlaceholderText(_translate("COM_ports_program", "The entered message is..."))
        self.clear.setText(_translate("COM_ports_program", "Clear"))
        self.label_5.setText(_translate("COM_ports_program", "COM-port :"))
        self.name_com_ports.setItemText(0, _translate("COM_ports_program", "COM5"))
        self.name_com_ports.setItemText(1, _translate("COM_ports_program", "COM6"))
        self.debug.setPlaceholderText(_translate("COM_ports_program", "                    Progress of the program..."))
